sudo: required
services:
  - docker

before_install:
  - docker build -t sarojmandal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sarojmandal/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-806286858093"
  bucket_path: "docker-react"
  on:
    branch: feature/test-aws
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_ACCESS_SECRET"